### The numpy dnarray: a mutidimensional array object

#### Arrays enable to perform mathematical operations on whole blocks of data using similar sytax

In [1]:
import numpy as np

In [2]:
# generate some random data
data = np.random.randn(2,3)
data

array([[ 2.89329207, -3.53883804,  0.114772  ],
       [-1.04665333, -0.65183474, -1.01477464]])

In [3]:
data * 10

array([[ 28.9329207 , -35.38838035,   1.14772   ],
       [-10.4665333 ,  -6.51834735, -10.14774643]])

In [4]:
data + data

array([[ 5.78658414, -7.07767607,  0.229544  ],
       [-2.09330666, -1.30366947, -2.02954929]])

#### An ndarray is a generic mutidimensional container for homogeous data, all the data must be same type. Every array has a shape. a tuple indicating the size of each dimension. And dtype an object describing the data type of the array

In [5]:
data.size

6

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

#### create ndarrays (list, nested sequences) - np.array()

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [10]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [12]:
array2 = np.array(data2)
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### in addition to np.array, there are a number of other functions for creating new arrays. As zeros and ones, create arrays of 0s and 1s. empty creates an array without initializing its value to any data type

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.empty((2,3,2))

array([[[ 0.00000000e+000, -2.32034772e+077],
        [ 3.45845952e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])