### The numpy dnarray: a mutidimensional array object

#### Arrays enable to perform mathematical operations on whole blocks of data using similar sytax

In [1]:
import numpy as np

In [2]:
# generate some random data
data = np.random.randn(2,3)
data

array([[ 0.38282512, -1.16453013, -1.58200635],
       [-0.5357254 ,  0.59223659, -1.4600507 ]])

In [3]:
data * 10

array([[  3.82825122, -11.64530134, -15.82006347],
       [ -5.357254  ,   5.92236592, -14.60050701]])

In [4]:
data + data

array([[ 0.76565024, -2.32906027, -3.16401269],
       [-1.0714508 ,  1.18447318, -2.9201014 ]])

#### An ndarray is a generic mutidimensional container for homogeous data, all the data must be same type. Every array has a shape. a tuple indicating the size of each dimension. And dtype an object describing the data type of the array

In [5]:
data.size

6

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### create ndarrays (list, nested sequences) - np.array()

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [11]:
array2 = np.array(data2)
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### in addition to np.array, there are a number of other functions for creating new arrays. As zeros and ones, create arrays of 0s and 1s. empty creates an array without initializing its value to any data type

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.empty((2,3,2))

array([[[ 1.28822975e-231, -2.00389261e+000],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 2.12199579e-314,  5.74084271e+169]],

       [[ 4.46648928e-090,  9.51182494e+169],
        [ 8.31967629e-072,  2.42382464e-052],
        [ 3.99910963e+252,  8.34404838e-309]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr1 = np.array([1,2,3], dtype= np.float64)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [19]:
arr2.dtype

dtype('int32')

### can explicly convert or cast an array from one dtype to amother using ndarray's astype method

In [20]:
arr = np.array([1,2,3,4,5])

In [21]:
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float64)

In [23]:
float_arr.dtype

dtype('float64')

#### if cast some floating-point number to be int, the decimal part will be truncated

#### astype always creates a new array, even if the new dtype is same as the old type

### arrays are import because they enable you to express batch operations on data without for loops -- vectorization

#### operations between ssame size arrays

In [24]:
arr = np.array([[1., 2.,3.],[4.,5.,6.]])

In [25]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [28]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [30]:
arr2 = np.array([[0., 4.,1.],[7.,2.,12.]])

In [31]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

#### operations between differently sized arrays is called broadcasting

### basic index and slicing

In [33]:
arr = np.array([0,1,2,3,4,5])

In [34]:
arr[5]

5

In [35]:
arr[2:5]

array([2, 3, 4])

In [36]:
arr[2:5]= 10

In [37]:
arr

array([ 0,  1, 10, 10, 10,  5])

#### array slices are views on the original array. That means that the data is not copied, and any modifications to the view will be reflected in the source array

In [38]:
arr_slice = arr[2:5]

In [39]:
arr_slice[1]= 100

In [40]:
arr

array([  0,   1,  10, 100,  10,   5])

In [41]:
arr_slice[:]=6

In [43]:
arr

array([0, 1, 6, 6, 6, 5])

#### If you want to a copy of a slice of an ndarray instead of a view, you will need to explicity copy the array arr[5:8].copy

In [44]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
arr2d[2]

array([7, 8, 9])

In [46]:
arr2d[2][2]

9

In [47]:
arr2d[2,2]

9